# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1898621516ef65a1587151c96c83e0d9b38110a5d53a83916a7d63d91e072191f2b0c6a2b86c380c753eb1e8eda7f4a6e9fcecc1a5d8dad777d48c56d278bcf6

test:
  secret_key_base: 1ad53c04905a938e2b7b082e36c319d74dd02f4a2a54dbb4222960eccaec148485b7227985399e6cc05424b9d47caf8c562b967ab91954df880174c56f5e6817

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
